project:
  type: website
  resources:
    - themes/

website:
  title: "Observatoire des indicateurs de la durabilité"

  sidebar:
    title: Observatoire des indicateurs de la durabilité
    style: docked
    search: true
    contents:
      - text: "Accueil"
        href: index.qmd
        
      - text: "---"
        
      - text: "Énergie"
        href: themes/1_energie.qmd
                
      - text: "Mobilité"
        href: themes/2_mobilite.qmd
        
      - text: "Climat"
        href: themes/3_climat.qmd


          
  search: 
    location: navbar
    type: textbox
     
format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true

lang: fr
language: 
  search-text-placeholder: Rechercher