project:
  type: website
  resources:
    - fiches/

website:
  title: "Indicateurs de l'Observatoire des indicateurs"

  sidebar:
    title: Observatoire des indicateurs
    style: docked
    search: true
    contents:
      - text: "Accueil"
        href: index.qmd
        
      - text: "---"
        
      - text: "Énergie"
        href: pages_thematiques/energie.qmd
        
      - text: "Climat"
        href: pages_thematiques/climat.qmd
        
      - text: "Mobilité"
        href: pages_thematiques/mobilite.qmd

          
  search: 
    location: navbar
    type: textbox
    
  announcement: 
     icon: info-circle
     dismissable: true
     content: "**Important** - Site déployé à l'aide de Quarto pour une maquette ObsInd"
     type: primary
     position: below-navbar
     
format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true




